### ISSUE TITLE
what's the license for this?

### ISSUE THREAD

**Issue by jz314** [pmcarlton/zotero-slack#1]
Hi pmcarlton, 
This is very helpful and I and probably others would like to use it. Do you have any restrictions and if not would you mind adding something like an MIT license to it?
Thanks!

**Comment by pmcarlton** [comment]
Hi,
There are no restrictions, I just put it here in case anyone found it useful.
The MIT license itself is bigger than this shell script, but I've added it to make it clear.
I hope it's useful for you! (I've stopped using Zotero myself)

**Comment by jz314** [comment]
Thanks so much!
